workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - ios_signing
      vars:
        BUNDLE_ID: "com.svutukuru.canadesi"
      node: v18.17.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up code signing
        script: |
          keychain initialize
          certificate add --certificate "$CM_CERTIFICATE" --certificate-password "$CM_CERTIFICATE_PASSWORD"
          profile add --profile "$CM_PROVISIONING_PROFILE"
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/CanaDesi.xcworkspace" \
            --scheme "CanaDesi"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true